### PR TITLE
Remove transparently extended interfaces

### PR DESCRIPTION
**Pull request by enov**
Remove `Cache_Arithmetic`, `Cache_GarbageCollect`, and `Cache_Tagging`
Also replace `HTTP_Request` occurances with `Kohana_HTTP_Request`

### CODE REVIEW

**Comment by acoulton** [comment]
@enov are you planning to remove all the transparent extensions for 3.4? 

If so, I think we should combine that with moving all the base classes to namespaces - if end users are going to have to go and update all the class names (and come up with some sort of dependency injection etc for their own custom extensions) in their projects they might as well replace with namespaced class names at that point. Otherwise they'll have to go and change all their code again to update `Kohana_Cache_Arithmetic` to `Kohana\Cache\Arithmetic` in future.

What do you think?

**Comment by enov** [comment]
> all the base classes to namespaces

By all, do you mean all base _classes_ and _interfaces_?

Yeah! :+1: I am for it!

**Comment by enov** [comment]
> @enov are you planning to remove all the transparent extensions for 3.4?

ATM, I am only removing transparently extended _interfaces_. As per the discussion in https://github.com/kohana/core/pull/563#issuecomment-61963732

**Comment by acoulton** [comment]
OK, that makes sense. Let's stick with just interfaces for now - I think maybe the classes needs more discussion.

**Pull request merged**
