### PR TITLE
Memcached support (Patch #4330)

### PR DESCRIPTION
**Pull request by nateless**
issue #4330

### CODE REVIEW

**Comment by kiall** [comment]
Apologies, Just restored CI server from backup .. Its not quite fixed yet ;) Ignore those last messages!

!build

**Comment by nateless** [comment]
It may failed because of the default settings. You need latest Memcached module installed, because even documentation doesn't have yet description about setOptions method. It also requires installed IGBINARY and Libketama. I can change default options to standard server configuration.

**Comment by kiall** [comment]
It looks like the config is causing a "ErrorException [ 1 ]: Class 'Memcached' not found ~ MODPATH/cache/config/cache.php [ 25 ]" exception.

Anyone who doesn't have the memcached extension installed will be unable to use the cache module in its current state :)

Also - Some unit tests would be great! You can basically just copy this and change 2x strings to get most of the tests...

https://github.com/kohana/cache/blob/3.2/master/tests/cache/SqliteTest.php

**Comment by ricardovf** [comment]
This comes in i good time as i was going to implement it. =)

Thx!

**Pull request closed without merging**
