### PR TITLE
Merge 3.2/master into 3.3/develop

### PR DESCRIPTION
**Pull request by enov**
Contains test cases for the bug [R4101](http://dev.kohanaframework.org/issues/4101)

Also a Memcache test that might be redundant because we have now another test extending the arithmetic tests.

### CODE REVIEW

**Comment by acoulton** [comment]
@enov good spot, I thought all these had been merged up already. Yes I think that Memcached test is redundant now (the arithmetic test also extends basic methods) so I guess we should merge it then delete that test class?

**Comment by enov** [comment]
> I guess we should merge it then delete that test class

Agreed.

**Comment by acoulton** [comment]
@enov done.

**Comment by enov** [comment]
Thanks @acoulton!

**Pull request merged**
