### PR TITLE
3.2/bug/4101 memcache lifetime

### PR DESCRIPTION
**Pull request by enov**
Adding Memcache test and the test cases mentioned in the bug 4101

http://dev.kohanaframework.org/issues/4101

The tests are running successfully. Therefore the bug should be marked as "works-for-me".

Thanks

### CODE REVIEW

**Comment by zeelot** [comment]
Try to reference the issue in the commits from now on :)

**Comment by enov** [comment]
You mean adding references in the code in form of comments?

**Comment by zeelot** [comment]
I mean your commit message should be something like "refs #1234 - Create MemcacheTest.php" so we know which ticket the commit is for

**Comment by enov** [comment]
Alright :+1:

**Pull request merged**
