### PR TITLE
Fixes #4303 Cache_File::get sometimes get into racing condition

### PR DESCRIPTION
**Pull request by d4rky-pl**
I'm using assets with path caching on my server. Because it goes through localhost, all requests are done almost simultaneously. This can lead to the racing condition where one request is asking for the cache file which the other request is currently saving. This leads to Kohana_Cache_File::get corrupted cache file exception because get() loads empty cache file (just created, not yet filled with data).

### CODE REVIEW

**Comment by kiall** [comment]
Humm .. I don't like the idea of masking corruption, just because that corruption **may** have been caused by a race condition...

**Comment by d4rky-pl** [comment]
Well, the "corruption" as you call it is simply an empty cache file so what's the difference? It'll simply be recached in the next iteration.

**Comment by samsoir** [comment]
I'm not sure I'm convinced of this, a semaphore or mutex would solve this issue properly rather than "hacking" apart the File_Driver.

Also; if this is a problem consider using a _real_ cache engine rather than file. File is crap - we all know it, now lets move on ;-)

**Comment by d4rky-pl** [comment]
Yes, I know it's crap, however it's fine for development purposes (like sqlite instead of "real" database system) and the problem I encountered happens exactly in development environment ;)

**Comment by kiall** [comment]
"Well, the "corruption" as you call it is simply an empty cache file so what's the difference?"
In your case, the corruption is an empty file caused by a race condition, so it makes little difference. Does this fix only cover up empty files which were caused by race conditions? That's the difference.

If my cache is busted, for whatever reason, I want to know about it so I can handle it. Your fix prevents me from doing that.

**Comment by d4rky-pl** [comment]
Then it should be sent into logs, but without throwing an error that causes website to crash. Busted cache should not be fatal to the user, only because your server environment is a lil' bit screwed up.

**Comment by samsoir** [comment]
"Then it should be sent into logs, but without throwing an error that causes website to crash. Busted cache should not be fatal to the user, only because your server environment is a lil' bit screwed up."

Which is why it throws an exception. You can handle that exception and gracefully move the user on without them knowing anything happened.

**Comment by d4rky-pl** [comment]
I still believe it should be a sane default but I see your point as valid.

**Pull request closed without merging**
