### PR TITLE
Return FALSE when inc/dec non-existent key on apcu

### PR DESCRIPTION
**Pull request by acoulton**
For compatibility with the standard Cache interface, implement the
legacy (backwards compatible) behaviour of incrementing or 
decrementing an undefined key in apcu.

Workaround for krakjoe/apcu#166

### CODE REVIEW

**Comment by acoulton** [comment]
@enov I'm not sure why this hasn't triggered a travis build, I've not run the tests locally but I think this is the correct resolution for the build failure in #81 - whatever the versioning of APCu the point of the Cache drivers is to provide a consistent interface across all backend cache implementations.

@neo22s this may be a breaking change for you if you're already using the apcu driver.

**Comment by neo22s** [comment]
Looks good, sure was breaking something. I never used APC as counter so not in my projects at least xD

Good to merge. Also should be in 3.4?

**Comment by enov** [comment]
> @enov I'm not sure why this hasn't triggered a travis build

https://github.com/kohana/cache/blob/3.3/bug/apcu-inc-dec-compatibility/.travis.yml#L8

**Comment by enov** [comment]
> whatever the versioning of APCu the point of the Cache drivers is to provide a consistent interface across all backend cache implementations.

:+1:

**Comment by enov** [comment]
@acoulton what would return `apcu_exists` when the user stores a key with `NULL` value?

**Comment by acoulton** [comment]
Ah I thought the travis branch config didn't apply to PR's but I guess they must be filtering the PR target branch.

>  what would return apcu_exists when the user stores a key with NULL value?

No idea, never used it and don't have it handy locally. I'd assume it returns TRUE, like array_exists. But AFAIK our tests/docs don't specify the behaviour of increment and decrement in that case for any driver - or if they do then apcu already behaves as we expect?

**Comment by enov** [comment]
I am afraid that those same tests will fail again, in case it returns `TRUE` for `NULL` values.

**Comment by enov** [comment]
On a side note, if we calculate a flag, say `$check_for_null`, on construct, it might be less costly (one less function to call) for those who are on older versions of APCu.

``` php
if ($check_for_null AND apcu_fetch($id) === NULL) {
    return FALSE;
}
return apcu_inc($id, $step);
```

**Comment by acoulton** [comment]
I don't think so, if the data provider gives `$start_state` as NULL the test skips the `$cahe->set` call. I can' t see any tests where actually set the value to NULL. It looks like that's an edge case that's never been considered (the structure of test and data provider makes it impossible to test just now).

You could have a cached flag as you suggest but frankly if your app is going to care about a couple of extra seeks of local shared memory I think Kohana (indeed, PHP) is probably not right for you. I think it's a premature optimisation that adds complexity for little benefit. Is an apcu_fetch/apcu_exists call really that much slower than referencing an instance variable?

**Comment by enov** [comment]
> as NULL the test skips the $cahe->set call

Bah! You're right! I did not notice that, I am sorry.

> You could have a cached flag as you suggest

I am not a micro-optimization freak :) but I just suggested that because of what this module is about (caching and optimization, that is).

**Pull request merged**
