### PR TITLE
Redis driver

### PR DESCRIPTION
**Pull request by dm**
Merged @marklocker redis driver into 3.3/develop

(Mark, it appears you didn't link your *.org.uk from git's user.email in your github account)

### CODE REVIEW

**Comment by enov** [comment]
Ah, this is so cool.

Should we merge and then add a test for it?

@acoulton?

**Comment by acoulton** [comment]
@enov it might be better to manually create a branch from this PR, then rebase and add the tests and travis config first so we can be sure all the return types etc are compatible?

**Comment by enov** [comment]
Alright, should this go into 3.3 or 3.4?

**Comment by enov** [comment]
Also there is an XCache driver in #30

**Comment by acoulton** [comment]
Well officially under semver I guess it should be in 3.4 as a new feature, same with the XCache driver. 

But it's tricky because these are basically ready to go, while 3.4 in core has a fair way to go. And Kohana doesn't really honour semver anyway (3.4 should really be 4.0 - so all our version numbers are sort of one more level of significant than the semver standard).

I wouldn't object to these coming into 3.3 since they're entirely new features and don't present any BC issues for anyone else?

**Pull request closed without merging**
