### PR TITLE
Calling mkdir with a NULL $context does not make directory

### PR DESCRIPTION
**Pull request by enov**
In the `_make_directory` wrapper, call `mkdir` with
respect to the availability of a passed $context
parameter.

Also removed a `mkdir` call in the `set` method
to use the `_make_directory` method instead.

### CODE REVIEW

**Comment by enov** [comment]
This is related to #53, #54

**Comment by acoulton** [comment]
@enov this looks good code-wise, the build error looks to be something composer/travis related. Have asked on #composer IRC to see if anyone knows what's happening.

Could merge now - I can't see this actual code will fail on 5.4 when it's working on all the others?

**Comment by enov** [comment]
> the build error looks to be something composer/travis related

yeah that's what it looks like. Thanks for asking in #composer IRC. Maybe we should wait to hear someone clarify?

**Comment by acoulton** [comment]
Sure, I've asked in #travis IRC too - will see if we hear anything. I restarted that build and it failed the same way, but oddly kohana/core seems to be building OK with the same composer version...

**Comment by enov** [comment]
> oddly kohana/core seems to be building OK with the same composer version...

that's very odd...

**Comment by acoulton** [comment]
Thanks to a reply in #composer I think it's composer/composer#264 - have disabled opcode caching in 9716747a8f which is building green.

You might like to rebase on 3.3/develop so we can see this green too, or we can just merge?

**Comment by enov** [comment]
> You might like to rebase on 3.3/develop

Yeah, I forgot to pull again before starting.

**Comment by acoulton** [comment]
I didn't notice that, I just meant to pick up my fix for the APC settings
that I just committed.

On 6 November 2014 10:23, Samuel Demirdjian notifications@github.com
wrote:

> You might like to rebase on 3.3/develop
> 
> Yeah, I forgot to pull again before starting.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kohana/cache/pull/59#issuecomment-61957225.

## 

Andrew Coulton
Founder
inGenerator Ltd

Follow us on Twitter @inGenerator
Phone us on 0131 510 0271

inGenerator Ltd is a company registered in Scotland (no SC435161) with its
registered office at 8 Craigleith Hill Row, Edinburgh EH4 2JX.

**Comment by acoulton** [comment]
Replaced by #60, now merged.

**Pull request closed without merging**
