### PR TITLE
Reinstate and fix skipped cache tests for 3.3

### PR DESCRIPTION
**Pull request by acoulton**
Continuing from #51 and kohana/kohana#50, this pull deals with the large number of currently skipped cache module tests. 

It will need a rebase after #51 is merged and travis is active directly on kohana/cache (I have activated on my fork for now). It also breaks at the moment until kohana/core#548 is merged.

**Wincache Driver**

We can't test this on Travis AFAIK and probably won't ever be able to. To reduce noise (so that we can spot unexpected skipped/incomplete tests more easily) I'd like to avoid those tests showing as skipped. I've come up with a hacky workaround here, any better solution would be welcome. Long-term we maybe need to consider whether the wincache driver really belongs here, or in a separate package with its own (windows) test environment - since the combination of rare production usage and no tests running is not good.

**Memcache Driver**

This has some [failing tests on HHVM](https://travis-ci.org/acoulton/cache/jobs/35711321) because of incompatible return types from native memcache methods:
- increment on an undefined key returns 0, not FALSE
- decrement on an undefined key returns 0, not FALSE
- get returns string for integer, float and boolean values (or set stores them incorrectly) - string and array are as expected.

I'll see if I can find any related HHVM issues - increment and decrement we could probably wrap and work around but the return type from get is more tricky. To keep the build green, we may need to convert these HHVM failures into skips in the short term (or configure travis to ignore HHVM as an allowed failure?).

### CODE REVIEW

**Comment by acoulton** [comment]
I didn't see any existing HHVM issues so have reported with standalone test cases as facebook/hhvm#3789 and facebook/hhvm#3790.

Since there doesn't seem to be a fix in the pipeline, I think we'll need to come up with a workaround - either:
- attempt to fix the return types in our driver
- convert failures to skips for these tests on HHVM
- add HHVM as an allowed failure (I'd prefer not to do this since all our other tests pass there)

**Comment by enov** [comment]
@acoulton I suggest we make an exception to this module and target `hhvm-nightly` instead of `hhvm` in Travis CI config, this way we can have the fixes made to HHVM in facebook/hhvm#3789 and facebook/hhvm#3790.

As per the release schedule [here](http://hhvm.com/blog/6083/hhvm-long-term-support), HHVM will probably have the fixes in version 3.4 in 6 Nov 2014.

**Comment by acoulton** [comment]
@enov using `hhvm-nightly` is a good idea but seems we can't do that either till perhaps end of october due to travis-ci/travis-ci#2812

**Comment by enov** [comment]
I suggest we merge this anyways.

We can open a ticket about why HHVM tests are failing, and keep it open until HHVM version 3.4 is available on Travis.

**Comment by acoulton** [comment]
@enov I'd rather we skip the relevant tests on HHVM and open a ticket to unskip them later - otherwise people will get complacent about the red cross on their commits which is not a good thing.

**Comment by enov** [comment]
:+1:

**Comment by acoulton** [comment]
@enov this is ready to review and merge

**Comment by enov** [comment]
This is an excellent PR @acoulton. Lots of things to learn from. Thanks.

**Comment by acoulton** [comment]
@enov thanks :)

**Comment by enov** [comment]
Just a bump here, as HHVM 3.4 will be available within a week:
https://github.com/travis-ci/travis-cookbooks/blob/master/changes.md#production-on-org-on-09122014

**Comment by enov** [comment]
@acoulton HHVM 3.4 should be available now on Travis.

**Pull request merged**
